version: 2

jobs:
  linux:
    docker:
      - image: swift
    steps:
      - checkout
      - run: apt-get update
      - run: apt-get install -yq libssl-dev
      - run: apt-get install -yq zlib1g-dev
      - run: swift build
      - run: swift test
workflows:
  version: 2
  tests:
    jobs:
      - linux
